### ISSUE TITLE
Migration for new fields: Use AFTER to keep order as in schema

### ISSUE THREAD

**Issue by cebe** [cebe/yii2-openapi#102]
Migrations for adding new columns should use "AFTER" keyword to make sure order of columns is the same as in schema.

**Comment by SOHELAHMED7** [comment]
I tested with MySQL.

I added new property in schema, then executed `./yii gii/api`. Migration for new column does not have [`after()`](https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchemaBuilder.php#L234) but when I apply newly created migration it automatically adds after the last column/property.

In which cases you are facing this issue?

**Comment by cebe** [comment]
@SOHELAHMED7 as far as I see this feature is complete. Please close the issue if that is the case.

**Comment by SOHELAHMED7** [comment]
Yes. this is completed. I cannot see close button. Seems like you have to close this issue
