### ISSUE TITLE
PathAutoCompletion causes timeouts on large projects

### ISSUE THREAD

**Issue by troncz** [cebe/yii2-openapi#145]
On large projects the current implementation of the PathAutoCompletion causes long execution times or timeouts. Since the autocomplete data is regenerated on every field rendered and there is no way to limit the path of the iterator, rendering of the view can take minutes.

**Comment by SOHELAHMED7** [comment]
Yes this needs a fix. 

![image](https://github.com/cebe/yii2-openapi/assets/6770119/82ce689c-8000-4478-8be3-51508800b878)

Meanwhile PR to fix this issue is in creation, you can use this lib at CLI `$ ./yii gii/api --help`

**Comment by SOHELAHMED7** [comment]
First priority will be given to values present in config ([example](https://github.com/cebe/yii2-openapi#usage)) to be shown in form fields.

Second to default values present in class cebe\yii2openapi\generator\ApiGenerator

Third will be given to values produced by PathAutoCompletion class
