### ISSUE TITLE
Create unimplemented methods in base controllers as abstract functions

### ISSUE THREAD

**Issue by cebe** [cebe/yii2-openapi#59]
![Bildschirmfoto von »2021-05-17 09-44-32«](https://user-images.githubusercontent.com/189796/118450551-9a2f5200-b6f4-11eb-9b05-23772cb31fb4.png)

these could be implemented as abstract functions and the TODO be moved to the imlementing controller.

**Comment by Insolita** [comment]
is it relevant to the checkAccess method also? Or only for actions?

**Comment by cebe** [comment]
can be done for all methods that have a "TODO" comment. Does not make sense to have a TODO in a file that is auto-generated as it can not be editied anyway, so making all these methods abstract makes sense to me.

**Comment by Insolita** [comment]
ok
