### ISSUE TITLE
Generate only API stuffs, Do not touch database: Possible?

### ISSUE THREAD

**Issue by mtangoo** [cebe/yii2-openapi#98]
Hi,
Can I generate only API stuffs using an existing database?
I would hand craft OpenAPI spec but if the module can generate template OA spec will be also nice.
I just do not want this module to change my database.

Is it possible?

**Comment by cebe** [comment]
yes, you can configure generator property `generateMigrations` to be `false`:

https://github.com/cebe/yii2-openapi/blob/3d4e93cc272b181dd0c9b8d6ec62636470eaae64/src/generator/ApiGenerator.php#L153-L156

**Comment by mtangoo** [comment]
Thanks @cebe

**Comment by cebe** [comment]
there should be some documentation about this.
